---
title: Meiru Mag
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A zine about asian-americans growing up in western culture
version: v1
baseurl: ''
url: 
permalink: "/title"
twitter_username: meirumag
github_username: jekyll
email: hi@meirumag.com
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
