---
# Site Settings
title: Meiru Mag
timezone: UTC
description: A zine about asian-americans growing up in western culture
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
version: v1
baseurl: ""
url:
permalink: "/title"

# Social
twitter_username: meirumag
github_username: jekyll
email: hi@meirumag.com

# Build Settings
markdown: kramdown
sass:
  style: compressed

# Excludes
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
