---
title: Meiru Meiru Meiru Meiru Meiru Meiru Meiru Meiru Meiru
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
version: v1
description: A magazine series about asian-americans growing up in western culture
baseurl: ''
url: ''
twitter_username: meirumag
github_username: jekyll
email: hi@meirumag.com
markdown: kramdown
permalink: :title
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
jekyll_get:
  data: team
  json: https://18f.gsa.gov/hub/api/team/
