---
#Site settings
title: Meiru Mag
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A zine about asian-americans growing up in western culture
version: "v1"
baseurl: ""
url: ""
permalink: "/title"

#Social links
twitter_username: meirumag
github_username: jekyll
email: hi@meirumag.com

#Build settings
markdown: kramdown
sass:
  style: compressed

#Exclude this stuff
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
